version: '3.7'
services:
  postgresql:
    image: postgres:14
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass

  node:
    image: node:16.14.0
    build: ./gate-simulator
    ports:
      - '9999:9999'
    command: "npm start"