version: '3.7'
services:
  mysql:
    image: mysql:8.0
    ports:
      - '3306:3306'
    volumes:
      - ./init_db:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass

  node:
    image: node:17
    user: "node"
    working_dir: /gate-simulator
    ports:
      - '9999:9999'
    volumes:
      - ./:/home/node/app
    environment:
      - NODE_ENV=production
    expose:
      - "8081"
    command: "npm start"